name: Post Image Notification to Slack

on:
  repository_dispatch:
    types: [new-image-completed]
  workflow_dispatch:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare image info
        id: vars
        run: |
          IMAGE_NAME="${{ github.event.client_payload.image_name }}"
          PRETTY_DATE=$(date -d "${{ github.event.client_payload.timestamp }}" +"%B %d, %Y at %H:%M UTC")
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "pretty_date=$PRETTY_DATE" >> $GITHUB_OUTPUT
          ISSUE_NUMBER="${{ github.event.client_payload.issue_number }}"
          REPO="${{ github.event.client_payload.repo }}"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Ensure image-count.txt exists
        run: |
          if [ ! -f image-count.txt ]; then
            touch image-count.txt
          fi

      - name: Calculate next image number and append new entry
        id: count
        run: |
          IMAGE_NUMBER=$(($(wc -l < image-count.txt) + 1))
          echo "image_number=$IMAGE_NUMBER" >> $GITHUB_OUTPUT
          echo "${{ steps.vars.outputs.image_name }},${{ steps.vars.outputs.pretty_date }}" >> image-count.txt

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Commit and push updated image-count.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add image ${{ steps.vars.outputs.image_name }} as #${{ steps.count.outputs.image_number }}"
          file_pattern: image-count.txt

      - name: Compose Slack message
        id: slack
        run: |
          ISSUE_LINK="https://github.com/${{ steps.vars.outputs.repo }}/issues/${{ steps.vars.outputs.issue_number }}"
          MSG=$(cat <<'EOF'
          '*Name:*' ${IMAGE_NAME}
          '*Number:*' ${IMAGE_NUMBER}
          '*Issue:*' <${ISSUE_LINK}|#${ISSUE_NUMBER}>
          '*Completed at:*' ${PRETTY_DATE}
          EOF
          )
          echo "message=$MSG" >> $GITHUB_OUTPUT
        env:
          IMAGE_NAME: ${{ steps.vars.outputs.image_name }}
          IMAGE_NUMBER: ${{ steps.count.outputs.image_number }}
          ISSUE_NUMBER: ${{ steps.vars.outputs.issue_number }}
          PRETTY_DATE: ${{ steps.vars.outputs.pretty_date }}
          REPO: ${{ steps.vars.outputs.repo }}

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Greetings! I am The Count. They call me the Count because I love to count ... things"}' \
            "$SLACK_WEBHOOK_URL"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"${{ steps.slack.outputs.message }}\"}" \
            "$SLACK_WEBHOOK_URL"
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Ah, Ah, Ah!"}' \
            "$SLACK_WEBHOOK_URL"
