name: Post Image Notification to Slack

on:
  repository_dispatch:
    types: [new-image-completed]

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Format Slack message
        id: format
        run: |
          msg=":camera: *New Image Completed*\n*Name:* ${{ github.event.client_payload.image_name }}\n*Number:* ${{ github.event.client_payload.image_number }}\n*Completed at:* ${{ github.event.client_payload.timestamp }}"
          echo "message=$msg" >> $GITHUB_OUTPUT

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"${{ steps.format.outputs.message }}\"}" "$SLACK_WEBHOOK_URL"
