name: Post Image Notification to Slack

on:
  repository_dispatch:
    types: [new-image-completed]
  workflow_dispatch:
    inputs:
      image_name:
        description: "Image name (title)"
        required: false
      issue_number:
        description: "Issue number"
        required: false
      repo:
        description: "Repo (owner/repo)"
        required: false
      timestamp:
        description: "Timestamp (UTC, e.g. '2025-05-28T20:25:00Z')"
        required: false

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Prepare image info
        id: vars
        run: |
          # Fallback logic for inputs/event data
          IMAGE_NAME="${{ github.event.client_payload.image_name }}"
         
