name: Post Image Notification to Slack

on:
  repository_dispatch:
    types: [new-image-completed]

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Format Slack message
        id: format
        run: |
          # Extract image name (last word of the title)
          IMAGE_NAME=$(echo "${{ github.event.client_payload.image_name }}" | awk '{print $NF}')
          # Format date prettily
          PRETTY_DATE=$(date -d "${{ github.event.client_payload.timestamp }}" +"%B %d, %Y at %H:%M UTC")
          # Compose Slack message
          echo "message=:camera: *New Image Completed*\n*Name:* $IMAGE_NAME\n*Number:* ${{ github.event.client_payload.image_number }}\n*Completed at:* $PRETTY_DATE" >> $GITHUB_OUTPUT

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"${{ steps.format.outputs.message }}\"}" "$SLACK_WEBHOOK_URL"
